### ISSUE TITLE
Can't find pod 'ActiveLook' on CocoaPods

### ISSUE THREAD

**Issue by BenoitFroment** [ActiveLook/ios-sdk#1]
Hi there,

Tried to follow the setup instructions and I'm stuck at 1s step : the pod seems not available on Cocoa

![image](https://user-images.githubusercontent.com/7375137/120192945-1b6e0500-c21c-11eb-9ca1-17a283c33f05.png)

**Comment by SylvainRomillon** [comment]
The pod is not yet release.
We have changed the readme

Sorry for the missunderstanding
