### ISSUE TITLE
Does this work with Standard Glasses version eg ENGO 2

### ISSUE THREAD

**Issue by mobile-appz** [ActiveLook/ios-sdk#17]
Hi does this SDK work with the  Standard Glasses version available on the main consumer shop eg ENGO 2 or do you need a to buy an enterprise development kit eg "ActiveLook ENTERPRISE - Smart AR glasses for the industry."

Are there any extra costs to enable this to connect to the glasses? Does this work with a  Apple Watch - glasses connection with no iphone?

**Comment by hypeitinc** [comment]
I have used it with Engo 1 and 2. No extra cost. Have not tried a watch implementation.

**Comment by mobile-appz** [comment]
> I have used it with Engo 1 and 2. No extra cost. Have not tried a watch implementation.

Great, thanks for the info

**Comment by CrewNerd** [comment]
The SDK works with the Apple Watch too. For my app (CrewNerd), the pairing UX is on the phone, but once you pair, the watch app will connect to the same device when used in "watch-only" mode.

**Comment by mobile-appz** [comment]
> The SDK works with the Apple Watch too. For my app (CrewNerd), the pairing UX is on the phone, but once you pair, the watch app will connect to the same device when used in "watch-only" mode.

Great, thanks for the info on this
