### ISSUE TITLE
ActiveLookSDK.shared() does not reflect its documentation

### ISSUE THREAD

**Issue by pierrerougeotf** [ActiveLook/ios-sdk#8]
The documentation for `ActiveLookSDK.shared` method states either to fill all parameters or to give no parameters at all to the method

>   // This is the method used to initialize the `ActiveLookSDK` singleton **and** access it later on.
>     // To initialize it, this function is called with all parameters set.
>     // To access it afterwards, just call it without any arguments: `ActiveLookSDK.shared()`
>     // - throws:
>     //     - `ActiveLookError.sdkInitMissingParameters`
>     //     if the function is called with incomplete parameters.
>     //     - `ActiveLookError.sdkCannotChangeParameters`
>     //     if the function is called more than once during the application's lifetime, with all the parameters correctly set.
>     // - parameters:
>     //     - token: The token used for authenticating with the firmware repository.
>     //     - onUpdateStart             Registered callback for update start event notification
>     //     - onUpdateProgress      Registered callback for update progress event notification.
>     //     - onUpdateSuccess       Registered callback for update success event notification.
>     //     - onUpdateError             Registered callback for update error event notification.
>     //  - returns: the `ActiveLookSDK`'s singleton
>     //

The method signature is not compliant with that 

``` 
public static func shared(token: String? = nil,
                              onUpdateStartCallback: startClosureSignature? = nil,
                              onUpdateProgressCallback: progressClosureSignature? = nil,
                              onUpdateSuccessCallback: successClosureSignature? = nil,
                              onUpdateFailureCallback: failureClosureSignature? = nil) throws -> ActiveLookSDK
```

Furthermore, in swift coding style Type names start with an uppercase

**Comment by pierrerougeotf** [comment]
Proposed patch
[issue-8.patch.zip](https://github.com/ActiveLook/ios-sdk/files/8163392/issue-8.patch.zip)

**Comment by hannesmnagel** [comment]
Are there any updates on this?
I am trying to use the sdk but it throws sdkInitMissingParameters. 
What do I need to fill in the parameters:
`try ActiveLookSDK.shared(reserved: <#T##String?#>, onUpdateStartCallback: <#T##StartClosureSignature?##StartClosureSignature?##(SdkGlassesUpdate) -> Void#>, onUpdateAvailableCallback: <#T##UpdateAvailableClosureSignature?##UpdateAvailableClosureSignature?##(SdkGlassesUpdate, () -> Void) -> Void#>, onUpdateProgressCallback: <#T##ProgressClosureSignature?##ProgressClosureSignature?##(SdkGlassesUpdate) -> Void#>, onUpdateSuccessCallback: <#T##SuccessClosureSignature?##SuccessClosureSignature?##(SdkGlassesUpdate) -> Void#>, onUpdateFailureCallback: <#T##FailureClosureSignature?##FailureClosureSignature?##(SdkGlassesUpdate) -> Void#>)`
